# 应用服务 WEB 访问端口
server:
  port: 8099
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/word_dictation?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8&noAccessToProcedureBodies=true&allowMultiQueries=true
    username: root
    password:
  redis:
    host: localhost
    password:
    database: 0
  mail:
    # 使用 smtp 协议
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: your-username
    # 授权码
    password: your-password
    test-connection: false
    properties.mail.smtp.auth: false
    properties.mail.debug: false
    properties.mail.mime.splitlongparameters: false
    default-encoding: UTF-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

custom:
  email:
    sender: your-sender

qiniu:
  accessKey: your-accessKey
  secretKey: your-secretKey
  bucketName: your-bucketName
  domain: your-domain
