# 应用服务 WEB 访问端口
server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/word_dictation?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8&noAccessToProcedureBodies=true&allowMultiQueries=true
    username: root
    password:
  redis:
    host: localhost
    password:
    database: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
