# 应用服务 WEB 访问端口
server:
  port: 8093
spring:
  datasource:
    url: jdbc:mysql://localhost:3336/word?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8&noAccessToProcedureBodies=true&allowMultiQueries=true
    username: word
    password: 123456
  redis:
    host: localhost
    password: root
    database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
