# 应用服务 WEB 访问端口
server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/exam_system?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8&noAccessToProcedureBodies=true&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: localhost
    password:
    database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl