# 应用服务 WEB 访问端口
server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://coclyun.top:3336/word_test?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8&noAccessToProcedureBodies=true&allowMultiQueries=true
    username: word_test
    password: 123456
  redis:
    host: localhost
    password:
    database: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
